config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :cart_flowers
  resources :cart_pots
  resources :carts
  resources :order_flowers
  resources :order_pots
  resources :orders
  resources :flowers
  resources :pots
  resources :users
  resource :session

  namespace :admin do
    resources :pots
    resources :flowers
    resources :orders
    resources :users

    get 'privileges' => 'pages#privileges'
    patch 'pots/:id/edit' => 'pots#update'
    delete 'pots/:id' => 'pots#destroy'
  end

  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'
  root 'pages#home'

  # patch 'cart_flowers/:id/add' => 'cartflowers#add_units', as: :add_cart_flower
  # patch 'cart_flowers/:id/remove' => 'cartflowers#remove_units', as: :remove_cart_flower

  delete 'cart/empty' => 'carts#empty'

  get 'order/pots' => 'pots#display_new_order_pot', as: :display_new_order_pot
  post 'order/pots' => 'pots#store_order_pots', as: :store_order_pots

  get 'order/pot/:pot_id/flowers' => 'flowers#display_new_order_flower', as: :display_new_order_flower
  post 'order/pot/:pot_id/flowers' => 'carts#store_order_flowers', as: :store_order_flowers

  get 'order/add_to_cart' => 'orders#display_order_before_cart', as: :display_order_before_cart
  post 'order/add_to_cart' => 'orders#add_order_to_cart', as: :add_order_to_cart

  get '404' => 'errors#not_found'
  get '422' => 'errors#unprocessable_entity'
  get '500' => 'errors#server_error'
end

app/models/cart_pot.rb
class CartPot < ApplicationRecord
  belongs_to :cart, inverse_of: :cart_pots
  belongs_to :pot

  has_many :cart_flowers, dependent: :destroy, inverse_of: :cart_pot
  has_many :flowers, through: :cart_flowers

  accepts_nested_attributes_for :cart_flowers

  def total_price
    pot.price + cart_flowers.sum(&:total_price)
  end

  def create_carts_flowers(flowers)
    flowers.each_pair { |key, val| cart_flowers.create(flower: Flower.find(key), units: val) }
  end
end

app/models/flower.rb
class Flower < ApplicationRecord
  has_many :comments, dependent: :destroy

  has_one_attached :flower_avatar

  # Paperclip
  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :order_flowers, dependent: :destroy
  has_many :order_pots, through: :order_flowers

  has_many :cart_flowers, dependent: :destroy
  has_many :cart_pots, through: :cart_flower

  validates :name, presence: true, uniqueness: true
  validates :price, numericality: {greater_than: 0}
  validates :color, format: { with: /[a-zA-Z]/ }
  validates :origin, format: { with: /[a-zA-Z]/ }
  validates :image, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  SORT_FILTER = [
    ['Name ascending', 'name_asc'],
    ['Name descending', 'name_desc'],
    ['Price ascending', 'price_asc'],
    ['Price descending', 'price_desc']
  ].freeze

  COUNTRY_FILTER = [
    'Spain',
    'Italy',
    'France'
  ].freeze

  COLOR_FILTER = [
    'Red',
    'White',
    'Lila',
    'Rosa',
    'Violet',
    'Orange'
  ]

  scope :name_asc, -> { order(name: :asc) }
  scope :name_desc, -> { order(name: :desc) }
  scope :price_asc, -> { order(price: :asc) }
  scope :price_desc, -> { order(price: :desc) }
  scope :location, ->(country) { where(origin: country) }
  scope :color, ->(color) { where(color: color) }

  def create_comment(content, current_user)
    comments.create!(text: content, user: current_user)
  end
end

app/controllers/admin/flowers_controller.rb
class Admin::FlowersController < Admin::AdminController
  def index
    @prompt = 'Sort by...'
    @flowers = Flower.all
    @flowers = @flowers.send(params[:sort]) unless params[:sort].blank?
  end

  def edit
    @flower = Flower.find(params[:id])
  end

  def update
    @flower = Flower.find(params[:id])
    if @flower.update(flower_params)
      redirect_to admin_flowers_path, notice: 'Flower successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @flower = Flower.find(params[:id])
    @flower.destroy
    redirect_to admin_flowers_path, notice: 'Flower successfully deleted!'
  end

  def new
    @flower = Flower.new
  end

  def create
    @flower = Flower.create(flower_params)
    if @flower.valid?
      redirect_to admin_flowers_path, notice: 'Flower successfully created!'
    else
      render :new
    end
  end

  private

  def flower_params
    params.require(:flower).permit(:name, :color, :origin, :price, :image, :avatar, :flower_avatar)
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :require_signin

  def display_new_order_flower
    @prompt = 'Sort by...'
    @prompt_country = 'Select origin...'
    @prompt_color = 'Select color...'
    @flowers = Flower.all

    @flowers = @flowers.send(params[:sort]) unless params[:sort].blank?
    @flowers = @flowers.location(params[:filter_country]) unless params[:filter_country].blank?
    @flowers = @flowers.color(params[:filter_color]) unless params[:filter_color].blank?
  end

  def index
    @flowers = Flower.includes(:comments).all
    # render json: @flowers
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @flowers }
    end
  end

  def show
    @flower = Flower.find(params[:id])
    @comments = @flower.comments
  end

  def update
    @flower = Flower.find(params[:id])
    @comment = @flower.create_comment(params[:comments], current_user)
  end
end

app/helpers/admin/flowers_helper.rb
module Admin::FlowersHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper


  def flower_id_correct?(id)
    Flower.find(id)   
  end


end

app/views/flowers/_cart_flower.html.erb
<%= image_tag(flower[:flower].image, size: "100x100") %>
<%= flower[:flower].name %>
Units: <%= flower[:units] %>

app/views/flowers/_flower.html.erb
<%= image_tag(order_flower.flower.image, size: "100x100") %>
<%= order_flower.flower.name %>
Units: <%= order_flower.units %>

<%= form_for(order_flower, remote: true) do |f| %>
  <p>
    <%= f.label :units %>
    <%= f.number_field :units, in: 0..4 %>
  </p>
  <%= f.submit 'Update' %>
<% end %>

app/views/flowers/_flower_info.html.erb
<li>
  <% if flower.flower_avatar.attached? %>
    <%= image_tag(flower.flower_avatar, size: "100x100") %>
  <% end %>

  <% if flower.avatar.present? %>
    <%= image_tag(flower.avatar.url, size: "100x100") %>
  <% end %>

  <%= image_tag(flower.image, size: "100x100") %>
  <p>Name: <%= flower.name %></p>
  <p>Color: <%= flower.color %></p>
  <p>Origin: <%= flower.origin %></p>
  <p>Price: <%= flower.price %> Euro</p>

  <% if current_user_admin? %>
    <button><%= link_to 'Edit', edit_admin_flower_path(flower.id) %></button>
    <button><%= link_to 'Delete', admin_flower_path(flower.id), method: :delete, data: { confirm: 'Are you sure?' } %></button> 
  <% end %>
</li>

app/views/flowers/_new_flower.html.erb
  <li>
    <%# check_box_tag("flower_ids[][#{flower.id}]", flower.id) %>
    <%= image_tag(flower.image, size: "100x100") %>
    <p>Name: <%= flower.name %></p>
    <p>Color: <%= flower.color %></p>
    <p>Origin: <%= flower.origin %></p>
    <p>Price: <%= flower.price %> Euro</p>
    <%= label_tag "units[#{flower.id}]", "Quantity:" %>
    <%= number_field_tag "units[#{flower.id}]", 0, within: 0..4 %>
  </li>

app/views/flowers/display_new_order_flower.html.erb
<section id="order-flowers">
  <h1>Please select the flowers</h1>
  
  <div>
    <%= form_tag display_new_order_flower_path, method: :get do %>
      <%= select_tag 'sort', options_for_select(Flower::SORT_FILTER, selected: params[:sort]), prompt: @prompt %>
      <%= select_tag 'filter_country', options_for_select(Flower::COUNTRY_FILTER, selected: params[:filter_country]), prompt: @prompt_country %>
      <%= select_tag 'filter_color', options_for_select(Flower::COLOR_FILTER, selected: params[:filter_color]), prompt: @prompt_color %>
      <%= submit_tag 'Apply' %>
    <% end %>
  </div>

  <% if @flowers.size != 0 %>
    <%= form_tag(display_new_order_flower_path) do |f| %>
      <fieldset>
        <ul>
          <%= render partial: 'flowers/new_flower', collection: @flowers, as: :flower %>
        </ul>
        <p>
          <%= submit_tag'Confirm' %>
          <%= link_to 'Cancel', root_path %>
        </p>
      </fieldset>
    <% end %> 
  <% else %>
    <p>Sorry, there are no flowers matching your request</p>
  <% end %>
</section>

<% content_for(:side) do %>
  <%= render partial: 'carts/side_cart' %>
<% end %>

app/views/flowers/index.html.erb
<section class="container">
  <h1>Flowers</h1>

  <% @flowers.each do |flower| %>
    <p><%= link_to flower.name, flower %></p>

      <% flower.comments.each do |comment| %>
        <p>- <%= comment.user.name %>said: </p>
        <p>- <%= comment.text %></p>
      <% end %>

  <% end %>
</section>

app/views/flowers/show.html.erb
<section class="container">
  <h1>Here it is! <%= @flower.name %></h1>

  <ul>
    <%= render partial: 'flowers/flower_info', locals: { flower: @flower } %>
  </ul>

  <h3>Comments:</h3>
    <div id="comments">
    <% if @comments.size != 0 %>
      <% @comments.each do |comment| %>
        <h4><%= comment.user.name %> said:</h4>
        <p><%= comment.text %></p>
        <button><%= link_to 'Delete', comment, method: :delete, remote: true %></button>
      <% end %>
    <% end %>
  </div>

  <%= form_tag flower_path, method: :patch, remote: true do %>
    <p><%= text_area_tag :comments, nil, rows: 2, cols: 60, placeholder: 'Write a comment...', id: 'comment_body' %></p>
    <p><%= submit_tag 'Add Comment' %></p>
  <% end %>
</section>

app/views/flowers/update.js.erb
$('#comments').append("<h4><%= j @comment.user.name %> said:</h4><p><%= j @comment.text %></p><button><%= escape_javascript link_to 'Delete', @comment, remote: true, method: :delete %></button>");
$('#comment_body').val(""); <!-- sets text area back to empty -->