config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :cart_flowers
  resources :cart_pots
  resources :carts
  resources :order_flowers
  resources :order_pots
  resources :orders
  resources :flowers
  resources :pots
  resources :users
  resource :session

  namespace :admin do
    resources :pots
    resources :flowers
    resources :orders
    resources :users

    get 'privileges' => 'pages#privileges'
    patch 'pots/:id/edit' => 'pots#update'
    delete 'pots/:id' => 'pots#destroy'
  end

  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'
  root 'pages#home'

  # patch 'cart_flowers/:id/add' => 'cartflowers#add_units', as: :add_cart_flower
  # patch 'cart_flowers/:id/remove' => 'cartflowers#remove_units', as: :remove_cart_flower

  delete 'cart/empty' => 'carts#empty'

  get 'order/pots' => 'pots#display_new_order_pot', as: :display_new_order_pot
  post 'order/pots' => 'pots#store_order_pots', as: :store_order_pots

  get 'order/pot/:pot_id/flowers' => 'flowers#display_new_order_flower', as: :display_new_order_flower
  post 'order/pot/:pot_id/flowers' => 'carts#store_order_flowers', as: :store_order_flowers

  get 'order/add_to_cart' => 'orders#display_order_before_cart', as: :display_order_before_cart
  post 'order/add_to_cart' => 'orders#add_order_to_cart', as: :add_order_to_cart

  get '404' => 'errors#not_found'
  get '422' => 'errors#unprocessable_entity'
  get '500' => 'errors#server_error'
end

app/models/flower.rb
class Flower < ApplicationRecord
  has_many :comments, dependent: :destroy

  has_one_attached :flower_avatar

  # Paperclip
  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :order_flowers, dependent: :destroy
  has_many :order_pots, through: :order_flowers

  has_many :cart_flowers, dependent: :destroy
  has_many :cart_pots, through: :cart_flower

  validates :name, presence: true, uniqueness: true
  validates :price, numericality: {greater_than: 0}
  validates :color, format: { with: /[a-zA-Z]/ }
  validates :origin, format: { with: /[a-zA-Z]/ }
  validates :image, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  SORT_FILTER = [
    ['Name ascending', 'name_asc'],
    ['Name descending', 'name_desc'],
    ['Price ascending', 'price_asc'],
    ['Price descending', 'price_desc']
  ].freeze

  COUNTRY_FILTER = [
    'Spain',
    'Italy',
    'France'
  ].freeze

  COLOR_FILTER = [
    'Red',
    'White',
    'Lila',
    'Rosa',
    'Violet',
    'Orange'
  ]

  scope :name_asc, -> { order(name: :asc) }
  scope :name_desc, -> { order(name: :desc) }
  scope :price_asc, -> { order(price: :asc) }
  scope :price_desc, -> { order(price: :desc) }
  scope :location, ->(country) { where(origin: country) }
  scope :color, ->(color) { where(color: color) }

  def create_comment(content, current_user)
    comments.create!(text: content, user: current_user)
  end
end

app/controllers/admin/flowers_controller.rb
class Admin::FlowersController < Admin::AdminController
  def index
    @prompt = 'Sort by...'
    @flowers = Flower.all
    @flowers = @flowers.send(params[:sort]) unless params[:sort].blank?
  end

  def edit
    @flower = Flower.find(params[:id])
  end

  def update
    @flower = Flower.find(params[:id])
    if @flower.update(flower_params)
      redirect_to admin_flowers_path, notice: 'Flower successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @flower = Flower.find(params[:id])
    @flower.destroy
    redirect_to admin_flowers_path, notice: 'Flower successfully deleted!'
  end

  def new
    @flower = Flower.new
  end

  def create
    @flower = Flower.create(flower_params)
    if @flower.valid?
      redirect_to admin_flowers_path, notice: 'Flower successfully created!'
    else
      render :new
    end
  end

  private

  def flower_params
    params.require(:flower).permit(:name, :color, :origin, :price, :image, :avatar, :flower_avatar)
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :require_signin

  def display_new_order_flower
    @prompt = 'Sort by...'
    @prompt_country = 'Select origin...'
    @prompt_color = 'Select color...'
    @flowers = Flower.all

    @flowers = @flowers.send(params[:sort]) unless params[:sort].blank?
    @flowers = @flowers.location(params[:filter_country]) unless params[:filter_country].blank?
    @flowers = @flowers.color(params[:filter_color]) unless params[:filter_color].blank?
  end

  def index
    @flowers = Flower.includes(:comments).all
    # render json: @flowers
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @flowers }
    end
  end

  def show
    @flower = Flower.find(params[:id])
    @comments = @flower.comments
  end

  def update
    @flower = Flower.find(params[:id])
    @comment = @flower.create_comment(params[:comments], current_user)
  end
end

app/helpers/admin/flowers_helper.rb
module Admin::FlowersHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper


  def flower_id_correct?(id)
    Flower.find(id)   
  end


end

app/views/admin/flowers/_form.html.erb
<%= form_for(flower, :url => url)do |f| %>
  <fieldset>
    <ul>
      <li>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </li>
      <li>
        <%= f.label :color %>
        <%= f.text_field :color %>
      </li>
      <li>
        <%= f.label :origin %>
        <%= f.text_field :origin %>
      </li>
      <li>
        <%= f.label :price %>
        <%= f.number_field :price %>
      </li>      
      <li>
        <%= f.label :image %>
        <%= f.text_field :image %>
      </li>
      <li>
        <%= f.label :flower_avatar %>
        <%= f.file_field :flower_avatar %>
      </li>
      <li>
        <%= f.label :avatar %>
        <%= f.file_field :avatar %>
      </li>
    </ul>
  </fieldset>
  <p>
    <%= f.submit %>
    <button><%= link_to "Cancel", admin_privileges_path %></button>
  </p>
<% end %>

app/views/admin/flowers/edit.html.erb
<h1>Edit Flower</h1>

<%= render 'shared/errors', object: @flower %>
<%= render partial: 'admin/flowers/form', locals: { flower: @flower, url: admin_flower_path} %>

app/views/admin/flowers/index.html.erb
<h1>There are <%= pluralize(@flowers.size, 'flower') %> on stock:</h1>

<div>
  <%= form_tag admin_flowers_path, method: :get do %>
    <%= select_tag 'sort', options_for_select(Flower::SORT_FILTER, selected: params[:sort]), prompt: @prompt, onchange: 'this.form.submit();' %>
  <% end %>
</div>

<ul class="flex f-wrap">
  <%= render partial: 'flowers/flower_info', collection: @flowers, as: :flower %>
</ul>

<hr>
<button><%= link_to 'Add New Flower', new_admin_flower_path %></button>
<p><%= link_to 'Go Back', admin_privileges_path %></p>

app/views/admin/flowers/new.html.erb
<h1>Add New Flower</h1>

<%= render 'shared/errors', object: @flower %>
<%= render partial: 'admin/flowers/form', locals: { flower: @flower, url: admin_flowers_path} %>