config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :cart_flowers
  resources :cart_pots
  resources :carts
  resources :order_flowers
  resources :order_pots
  resources :orders
  resources :flowers
  resources :pots
  resources :users
  resource :session

  namespace :admin do
    resources :pots
    resources :flowers
    resources :orders
    resources :users

    get 'privileges' => 'pages#privileges'
    patch 'pots/:id/edit' => 'pots#update'
    delete 'pots/:id' => 'pots#destroy'
  end

  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'
  root 'pages#home'

  # patch 'cart_flowers/:id/add' => 'cartflowers#add_units', as: :add_cart_flower
  # patch 'cart_flowers/:id/remove' => 'cartflowers#remove_units', as: :remove_cart_flower

  delete 'cart/empty' => 'carts#empty'

  get 'order/pots' => 'pots#display_new_order_pot', as: :display_new_order_pot
  post 'order/pots' => 'pots#store_order_pots', as: :store_order_pots

  get 'order/pot/:pot_id/flowers' => 'flowers#display_new_order_flower', as: :display_new_order_flower
  post 'order/pot/:pot_id/flowers' => 'carts#store_order_flowers', as: :store_order_flowers

  get 'order/add_to_cart' => 'orders#display_order_before_cart', as: :display_order_before_cart
  post 'order/add_to_cart' => 'orders#add_order_to_cart', as: :add_order_to_cart

  get '404' => 'errors#not_found'
  get '422' => 'errors#unprocessable_entity'
  get '500' => 'errors#server_error'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cart_pots, dependent: :destroy, inverse_of: :cart
  has_many :pots, through: :cart_pots

  accepts_nested_attributes_for :cart_pots

  def total_price
    cart_pots.sum(&:total_price)
  end

  def create_cart_pot(pot, flowers)
    cart_pot = cart_pots.create(pot: pot)
    cart_pot.create_carts_flowers(flowers)
  end

  def empty
    cart_pots.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_signin

  def store_order_flowers
    flowers = params[:units].reject { |_key, value| value.to_i.zero? }
    pot = Pot.find(params[:pot_id])
    pot_capacity = pot.capacity
    number_flowers = number_flowers_selected(flowers)
    enough_capacity = enough_capacity?(flowers, pot_capacity)

    if number_flowers && enough_capacity
      current_cart.create_cart_pot(pot, flowers)
      redirect_to current_user
    else
      @flowers = Flower.all
      flash.now[:alert] = 'Please select at least one flower' unless number_flowers
      flash.now[:alert] = "You have selected to many flowers! Maximum: #{pot_capacity}" unless enough_capacity
      render template: 'flowers/display_new_order_flower'
    end
  end

  def empty
    current_cart.empty
    redirect_to current_user
  end

  private

  def number_flowers_selected(selection)
    selection.values.map(&:to_i).reduce(:+)
  end

  def enough_capacity?(selection, capacity)
    capacity >= number_flowers_selected(selection).to_i
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% current_cart.cart_pots.each_with_index do |cart_pot, i| %>
  <li id='cart_pot_<%= cart_pot.id %>'>
    <%= render partial: 'cart_pots/cart_pot', locals: { cart_pot: cart_pot } %>
  </li>
<% end %>

app/views/carts/_cart_info.html.erb
<h1>Your Cart</h1>
    
<% if current_cart.cart_pots.size !=0 %>
  <ul class="flex">
    <%= render 'carts/cart' %>
    <p>
    <button><%= link_to 'Empty entire cart', cart_empty_path, method: :delete %></button>
    <button><%= link_to 'Add further stuff to cart', display_new_order_pot_path %></button>
    </p>
  </ul>

  <div>
    <h3 id='total_price'>Total price: <%= current_user.total_orders_price_in_cart %> </h3>
    <button><%= link_to 'ORDER THESE PRODUCTS', new_order_path %></button>
  </div>

<% else %>
  <p>Your cart is currently empty!</p>
  <button><%= link_to 'New Order', display_new_order_pot_path%></button>
<% end %>

app/views/carts/_side_cart.html.erb
<% if current_user && current_cart.cart_pots.size != 0 %>
  <h1>Your Cart</h1>

  <% current_cart.pots.each_with_index do |pot, i| %>
    <ul>
      <li>Pot: 
        <%= pot.name %>
        <%= pot.dimensions %>
        <%= pot.material %>
        <%= pot.price %>

        <p>Flowers:
        <% current_cart.cart_pots[i].flowers.each_with_index do |flower, j| %>
          <%= flower.name %>(<%= current_cart.cart_pots[i].cart_flowers[j].units %>)
        <% end %>
        </p>

        <p>Individual Price: <%= current_cart.cart_pots[i].total_price %></p>
      </li>
    </ul>
  <% end %>
  <h3>Total price: <%= current_user.total_orders_price_in_cart %> </h3>
<% end %>