config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :cart_flowers
  resources :cart_pots
  resources :carts
  resources :order_flowers
  resources :order_pots
  resources :orders
  resources :flowers
  resources :pots
  resources :users
  resource :session

  namespace :admin do
    resources :pots
    resources :flowers
    resources :orders
    resources :users

    get 'privileges' => 'pages#privileges'
    patch 'pots/:id/edit' => 'pots#update'
    delete 'pots/:id' => 'pots#destroy'
  end

  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'
  root 'pages#home'

  # patch 'cart_flowers/:id/add' => 'cartflowers#add_units', as: :add_cart_flower
  # patch 'cart_flowers/:id/remove' => 'cartflowers#remove_units', as: :remove_cart_flower

  delete 'cart/empty' => 'carts#empty'

  get 'order/pots' => 'pots#display_new_order_pot', as: :display_new_order_pot
  post 'order/pots' => 'pots#store_order_pots', as: :store_order_pots

  get 'order/pot/:pot_id/flowers' => 'flowers#display_new_order_flower', as: :display_new_order_flower
  post 'order/pot/:pot_id/flowers' => 'carts#store_order_flowers', as: :store_order_flowers

  get 'order/add_to_cart' => 'orders#display_order_before_cart', as: :display_order_before_cart
  post 'order/add_to_cart' => 'orders#add_order_to_cart', as: :add_order_to_cart

  get '404' => 'errors#not_found'
  get '422' => 'errors#unprocessable_entity'
  get '500' => 'errors#server_error'
end

app/models/pot.rb
class Pot < ApplicationRecord
  has_many :order_pots, dependent: :destroy
  has_many :orders, through: :order_pots

  has_many :cart_pots, dependent: :destroy
  has_many :carts, through: :cart_pots

  validates :name, uniqueness: true
  validates :material, presence: true
  validates :price, numericality: {greater_than: 0}
  validates :dimensions, format: {
    with: /\d/,
    message: "must include numerical values"
  }
  validates :capacity, numericality: {only_integer: true, greater_than: 0}
  validates :image, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  SORT_FILTER = [
    ['Name ascending', 'name_asc'],
    ['Name descending', 'name_desc'],
    ['Price ascending', 'price_asc'],
    ['Price descending', 'price_desc']
  ].freeze

  scope :name_asc, -> { order(name: :asc) }
  scope :name_desc, -> { order(name: :desc) }
  scope :price_asc, -> { order(price: :asc) }
  scope :price_desc, -> { order(price: :desc) }

  def self.exists?(id)
    Pot.find_by(id: id)
  end

end

app/controllers/admin/pots_controller.rb
class Admin::PotsController < Admin::AdminController
  def index
    @prompt = 'Sort by...'
    @pots = Pot.all
    @pots = @pots.send(params[:sort]) unless params[:sort].blank?
  end

  def edit
    @pot = Pot.find(params[:id])
  end

  def update
    @pot = Pot.find(params[:id])
    if @pot.update(pot_params)
      redirect_to admin_pots_path, notice: 'Pot successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @pot = Pot.find(params[:id])
    @pot.destroy
    redirect_to admin_pots_path, notice: 'Pot successfully deleted!'
  end

  def new
    @pot = Pot.new
  end

  def create
    @pot = Pot.create(pot_params)
    if @pot.valid?
      redirect_to admin_pots_path, notice: 'Pot successfully created!'
    else
      render :new
    end
  end

  private

  def pot_params
    params.require(:pot).permit(:name, :dimensions, :material, :price, :image, :capacity)
  end
end

app/controllers/pots_controller.rb
class PotsController < ApplicationController
  before_action :require_signin

  def display_new_order_pot
    @prompt = 'Sort by...'
    @pots = Pot.all
    @pots = @pots.send(params[:sort]) unless params[:sort].blank?
  end

  def store_order_pots
    pot_id = params[:pot_id]
    if Pot.exists?(pot_id)
      redirect_to display_new_order_flower_path(pot_id)
    else
      render :display_new_order_pot
    end
  end
end

app/helpers/pots_helper.rb
module PotsHelper


end

app/views/admin/pots/_form.html.erb
<%= form_for(pot, :url => url)do |f| %>
  <fieldset>
    <ul>
      <li>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </li>
      <li>
        <%= f.label :dimensions %>
        <%= f.text_field :dimensions %>
      </li>
      <li>
        <%= f.label :material %>
        <%= f.text_field :material %>
      </li>
      <li>
        <%= f.label :price %>
        <%= f.number_field :price %>
      </li>      
      <li>
        <%= f.label :image %>
        <%= f.text_field :image %>
      </li>
      <li>
        <%= f.label :capacity %>
        <%= f.text_field :capacity %>
      </li>
    </ul>
  </fieldset>
  <p>
    <%= f.submit %>
    <button><%= link_to "Cancel", admin_privileges_path %></button>
  </p>
<% end %>

app/views/admin/pots/edit.html.erb
<h1>Edit Pot</h1>

<%= render 'shared/errors', object: @pot %>
<%= render partial: 'admin/pots/form', locals: { pot: @pot, url: admin_pot_path} %>

app/views/admin/pots/index.html.erb
<h1>There are <%= pluralize(@pots.size, 'pot') %> on stock:</h1>

<div>
  <%= form_tag admin_pots_path, method: :get do %>
    <%= select_tag 'sort', options_for_select(Pot::SORT_FILTER, selected: params[:sort]), prompt: @prompt, onchange: 'this.form.submit();' %>
  <% end %>
</div>

<%= render partial: 'pots/pot', collection: @pots, as: :pot %>

<hr>
<button><%= link_to 'Add New Pot', new_admin_pot_path %></button>
<p><%= link_to 'Go Back', admin_privileges_path %></p>

app/views/admin/pots/new.html.erb
<h1>Add New Pot</h1>

<%= render 'shared/errors', object: @pot %>
<%= render partial: 'admin/pots/form', locals: { pot: @pot, url: admin_pots_path} %>